apiVersion: apps/v1
kind: Deployment
metadata:
  name: trans-bbs-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trans-bbs
  template:
    metadata:
      labels:
        app: trans-bbs
    spec:
      containers:
      - name: trans-bbs-container
        image: localhost:32000/trans-bbs:v2
        ports:
        - containerPort: 5000
