apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
type: Opaque
stringData:
  NEXTCLOUD_ADMIN_USER: negisyon
  NEXTCLOUD_ADMIN_PASSWORD: xxxxx
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: password
